# Generated by Django 3.2.11 on 2022-06-09 11:42

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.blocks
import wagtail.fields
import wagtail.documents.blocks
import wagtail.images.blocks
import wagtail.snippets.blocks
import wtpages.blocks
import wtpages.csstheme


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('wagtailimages', '0023_add_choose_permissions'),
        ('wagtailcore', '0066_collection_management_permissions'),
        ('wagtailvideos', '0012_remove_unique_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='CssTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('color', models.CharField(blank=True, max_length=255)),
                ('background', models.CharField(blank=True, max_length=255)),
                ('title_color', models.CharField(blank=True, max_length=255)),
                ('title_background', models.CharField(blank=True, max_length=255)),
                ('css_class', models.CharField(blank=True, max_length=255, null=True)),
                ('css', models.TextField(blank=True, help_text='Raw CSS. There are NO validation, please be careful. {theme} should precede any selector.', verbose_name='Css')),
            ],
            options={
                'verbose_name': 'Css Theme',
                'verbose_name_plural': 'Css Themes',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='JsCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('doc_position', models.CharField(choices=[('doc_end', 'End of document (before </body>)'), ('doc_beg', 'Beginning of document (after <body>)'), ('head', 'Head (inside <head>)')], default='doc_end', max_length=10)),
                ('text', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LanguageRedirectionPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='WtBasePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('seo_keywords', models.TextField(blank=True, verbose_name='SEO keywords')),
                ('show_in_sitemap', models.BooleanField(default=True)),
                ('hero_video_loop', models.BooleanField(default=False)),
                ('hero_title', models.CharField(blank=True, max_length=255, null=True)),
                ('hero_text', wagtail.fields.RichTextField(blank=True, verbose_name='Hero Text')),
                ('hero_links', wagtail.fields.StreamField([('internal_page_link', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(icon='title', label='Title')), ('link_type', wagtail.blocks.ChoiceBlock(choices=[('link', 'Link'), ('button', 'Button')], label='Link Type')), ('new_window', wagtail.blocks.BooleanBlock(label='Open link in new window', required=False)), ('link', wagtail.blocks.PageChooserBlock(label='Internal Page link', required=True))], icon='title', label='Internal Page Link')), ('external_page_link', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(icon='title', label='Title')), ('link_type', wagtail.blocks.ChoiceBlock(choices=[('link', 'Link'), ('button', 'Button')], label='Link Type')), ('new_window', wagtail.blocks.BooleanBlock(label='Open link in new window', required=False)), ('link', wagtail.blocks.URLBlock(label='External link', required=True))], icon='title', label='External Link')), ('phone_link', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(icon='title', label='Title')), ('link_type', wagtail.blocks.ChoiceBlock(choices=[('link', 'Link'), ('button', 'Button')], label='Link Type')), ('new_window', wagtail.blocks.BooleanBlock(label='Open link in new window', required=False)), ('link', wagtail.blocks.CharBlock(label='Phone Link', required=True))], icon='title', label='Phone Link')), ('email_link', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(icon='title', label='Title')), ('link_type', wagtail.blocks.ChoiceBlock(choices=[('link', 'Link'), ('button', 'Button')], label='Link Type')), ('new_window', wagtail.blocks.BooleanBlock(label='Open link in new window', required=False)), ('link', wagtail.blocks.EmailBlock(label='Email Link', required=True))], icon='title', label='Email Link')), ('form_link', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(icon='title', label='Title')), ('link_type', wagtail.blocks.ChoiceBlock(choices=[('link', 'Link'), ('button', 'Button')], label='Link Type')), ('new_window', wagtail.blocks.BooleanBlock(label='Open link in new window', required=False)), ('link', wtpages.blocks.FormChoserBlock(label='Pop Up Form link', required=True))], icon='title', label='Popup Form')), ('doc_link', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(icon='title', label='Title')), ('link_type', wagtail.blocks.ChoiceBlock(choices=[('link', 'Link'), ('button', 'Button')], label='Link Type')), ('new_window', wagtail.blocks.BooleanBlock(label='Open link in new window', required=False)), ('link', wagtail.documents.blocks.DocumentChooserBlock(label='Document', required=True))], icon='title', label='Document Link'))], blank=True, null=True)),
                ('hero_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailvideos.video', verbose_name='Hero Video')),
                ('open_graph_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wtpages.csstheme', verbose_name='Theme')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='StandardPage',
            fields=[
                ('wtbasepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wtpages.wtbasepage')),
                ('redirect_to_first_child', models.BooleanField(default=False, help_text='Show the first child page instead of showing this one')),
                ('stream_field', wagtail.fields.StreamField([('paragraph', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(form_classname='full', icon='title', label='Title', required=False)), ('title_2', wagtail.blocks.CharBlock(icon='title', label='Title 2nd Line', required=False)), ('title_tag', wagtail.blocks.ChoiceBlock(choices=[('h1', 'H1'), ('h2', 'H2'), ('h3', 'H3')], label='Title Tag')), ('text_align', wagtail.blocks.ChoiceBlock(choices=[('left', 'Left'), ('right', 'Right'), ('center', 'Center')], label='Text Align')), ('text', wagtail.blocks.RichTextBlock(form_classname='full', label='Text', required=False)), ('new_links', wagtail.blocks.StructBlock([('align', wagtail.blocks.ChoiceBlock(choices=[('text-left', 'Left'), ('text-center', 'Center'), ('text-right', 'Right')], label='Align Links')), ('links', wagtail.blocks.StreamBlock([('internal_page_link', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(icon='title', label='Title')), ('link_type', wagtail.blocks.ChoiceBlock(choices=[('link', 'Link'), ('button', 'Button')], label='Link Type')), ('new_window', wagtail.blocks.BooleanBlock(label='Open link in new window', required=False)), ('link', wagtail.blocks.PageChooserBlock(label='Internal Page link', required=True))], icon='title', label='Internal Page Link')), ('external_page_link', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(icon='title', label='Title')), ('link_type', wagtail.blocks.ChoiceBlock(choices=[('link', 'Link'), ('button', 'Button')], label='Link Type')), ('new_window', wagtail.blocks.BooleanBlock(label='Open link in new window', required=False)), ('link', wagtail.blocks.URLBlock(label='External link', required=True))], icon='title', label='External Page Link')), ('phone_link', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(icon='title', label='Title')), ('link_type', wagtail.blocks.ChoiceBlock(choices=[('link', 'Link'), ('button', 'Button')], label='Link Type')), ('new_window', wagtail.blocks.BooleanBlock(label='Open link in new window', required=False)), ('link', wagtail.blocks.CharBlock(label='Phone Link', required=True))], icon='title', label='Phone Link')), ('email_link', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(icon='title', label='Title')), ('link_type', wagtail.blocks.ChoiceBlock(choices=[('link', 'Link'), ('button', 'Button')], label='Link Type')), ('new_window', wagtail.blocks.BooleanBlock(label='Open link in new window', required=False)), ('link', wagtail.blocks.EmailBlock(label='Email Link', required=True))], icon='title', label='Email Link')), ('form_link', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(icon='title', label='Title')), ('link_type', wagtail.blocks.ChoiceBlock(choices=[('link', 'Link'), ('button', 'Button')], label='Link Type')), ('new_window', wagtail.blocks.BooleanBlock(label='Open link in new window', required=False)), ('link', wtpages.blocks.FormChoserBlock(label='Pop Up Form link', required=True))], icon='title', label='Popup Form')), ('doc_link', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(icon='title', label='Title')), ('link_type', wagtail.blocks.ChoiceBlock(choices=[('link', 'Link'), ('button', 'Button')], label='Link Type')), ('new_window', wagtail.blocks.BooleanBlock(label='Open link in new window', required=False)), ('link', wagtail.documents.blocks.DocumentChooserBlock(label='Document', required=True))], icon='title', label='Document Link'))], label='Links', required=False))], label='Related Links', required=False))], icon='pilcrow', label='Text')), ('gallery', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(form_classname='full', icon='title', label='Title', required=False)), ('title_tag', wagtail.blocks.ChoiceBlock(choices=[('h1', 'H1'), ('h2', 'H2'), ('h3', 'H3')], label='Title Tag')), ('mode', wagtail.blocks.ChoiceBlock(choices=[('lt-12', 'Thumbnails'), ('12', 'Different Shapes')])), ('full_width', wagtail.blocks.BooleanBlock(default=False, required=False)), ('images', wagtail.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock, label='Images'))], icon='pilcrow', label='Gallery', required=False)), ('gallery_collections', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(form_classname='full', icon='title', label='Title', required=False)), ('title_tag', wagtail.blocks.ChoiceBlock(choices=[('h1', 'H1'), ('h2', 'H2'), ('h3', 'H3')], label='Title Tag')), ('show_categories', wagtail.blocks.BooleanBlock(required=False)), ('show_image_title', wagtail.blocks.BooleanBlock(required=False)), ('mode', wagtail.blocks.ChoiceBlock(choices=[('lt-12', 'Thumbnails'), ('12', 'Different Shapes')])), ('full_width', wagtail.blocks.BooleanBlock(required=False)), ('theme', wagtail.snippets.blocks.SnippetChooserBlock(wtpages.csstheme.CssTheme, required=False)), ('gallery_collections', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(form_classname='full', icon='title', label='Title')), ('collection', wtpages.blocks.CollectionChoserBlock(label='Gallery Collection', required=False)), ('tag', wtpages.blocks.ImageTagChoserBlock(label='Image Tag', required=False))]), label='Gallery Collections', required=True))], icon='pilcrow', label='Gallery (Collections)', required=False)), ('carousel', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(form_classname='full', icon='title', label='Title', required=False)), ('title_tag', wagtail.blocks.ChoiceBlock(choices=[('h1', 'H1'), ('h2', 'H2'), ('h3', 'H3')], label='Title Tag')), ('text', wagtail.blocks.TextBlock(icon='text', label='Text', required=False)), ('text_layout', wagtail.blocks.ChoiceBlock(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], icon='title', label='Text Layout')), ('show_controls', wagtail.blocks.BooleanBlock(icon='title', label='Show Arrows', required=False)), ('full_width', wagtail.blocks.BooleanBlock(icon='title', label='Full Width', required=False)), ('show_tint', wagtail.blocks.BooleanBlock(icon='title', label='Show Tint', required=False)), ('theme', wagtail.snippets.blocks.SnippetChooserBlock(wtpages.csstheme.CssTheme, required=False)), ('image_size', wagtail.blocks.ChoiceBlock(choices=[('regular', 'Regular'), ('full', 'Full Screen'), ('condensed', 'Condensed'), ('inside', 'Inside Text')], label='Image Size')), ('images', wagtail.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock, label='Images', required=False))], icon='pilcrow', label='Carousel')), ('site_map', wagtail.blocks.StructBlock([], icon='pilcrow', label='Site Map')), ('raw_html', wagtail.blocks.StructBlock([('text', wagtail.blocks.TextBlock(icon='title', label='HTML', required=True))], icon='pilcrow', label='Raw HTML'))], blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Text Page',
            },
            bases=('wtpages.wtbasepage',),
        ),
        migrations.CreateModel(
            name='WtBasePageBackgroundImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_images', to='wtpages.wtbasepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='URLPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('link_external', models.URLField(blank=True, null=True)),
                ('external', models.BooleanField(default=False, help_text='Open link in a new window')),
                ('link_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document')),
                ('link_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'URL Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='JsCodePlacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jscode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wtpages.jscode')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='js_code_placements', to='wagtailcore.page')),
            ],
        ),
        migrations.CreateModel(
            name='JsCodePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('jscode', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='wtpages.jscode')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JsCodeExcludePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('jscode', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclude_pages', to='wtpages.jscode')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CssThemeImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('position', models.CharField(choices=[('top_left', 'Top Left'), ('top_middle', 'Top Middle'), ('top_right', 'Top Right'), ('right_middle', 'Right Middle'), ('bottom_right', 'Bottom Right'), ('bottom_middle', 'Bottom Middle'), ('bottom_left', 'Bottom Left'), ('left_middle', 'Left Middle')], default='left', max_length=20)),
                ('background_size', models.CharField(blank=True, max_length=255, null=True)),
                ('background_position', models.CharField(blank=True, max_length=255, null=True)),
                ('scroll_animate', models.BooleanField(default=False)),
                ('inside_container', models.BooleanField(default=False)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('theme', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='wtpages.csstheme')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
