# Generated by Django 3.2.11 on 2022-06-09 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('wtpages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WtBasePageBackgroundImages',
            new_name='WtBasePageHeroImages',
        ),
    ]
