# Generated by Django 3.2.11 on 2022-06-09 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('wtpages', '0002_rename_wtbasepagebackgroundimages_wtbasepageheroimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wtbasepageheroimages',
            name='image',
        ),
        migrations.AddField(
            model_name='wtbasepageheroimages',
            name='hero_image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image'),
            preserve_default=False,
        ),
    ]
