# Generated by Django 3.2.11 on 2022-06-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtpages', '0003_auto_20220609_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='wtbasepage',
            name='hero_text_align',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='left', max_length=10),
        ),
    ]
