# Generated by Django 3.2.11 on 2022-06-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtpages', '0021_alter_standardpage_stream_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='wtbasepage',
            name='show_navbar',
            field=models.BooleanField(default=False),
        ),
    ]
