# Generated by Django 3.2.11 on 2022-06-15 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtpages', '0024_alter_standardpage_stream_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wtbasepage',
            name='hero_text',
            field=models.TextField(blank=True, verbose_name='Hero Text'),
        ),
    ]
