# Generated by Django 3.2.11 on 2022-06-15 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wtpages', '0029_alter_standardpage_stream_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wtbasepageheroimages',
            old_name='hero_image',
            new_name='image',
        ),
    ]
