# Generated by Django 3.2.11 on 2022-07-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtpages', '0044_alter_standardpage_stream_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='wtbasepage',
            name='hero_mobile_half_height',
            field=models.BooleanField(default=True, verbose_name='Half height on mobile'),
        ),
    ]
