# Generated by Django 3.2.11 on 2023-10-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtpages', '0054_alter_standardpage_stream_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='wtbasepage',
            name='color_theme',
            field=models.CharField(choices=[('default', 'Default'), ('white', 'White')], default='default', max_length=20),
        ),
    ]
