# Generated by Django 3.2.18 on 2026-02-27 05:03

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wtpages', '0062_alter_standardpage_stream_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='wtbasepage',
            name='logos_banner',
            field=wagtail.fields.StreamField([('logo', wagtail.blocks.StructBlock([('logo', wagtail.images.blocks.ImageChooserBlock(label='Logo', required=True)), ('link', wagtail.blocks.URLBlock(label='Link', required=False))], icon='title', label='Logo'))], blank=True, null=True),
        ),
    ]
