# Generated by Django 3.2.11 on 2022-06-09 11:42

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractiveMaps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('layout_image', models.ForeignKey(blank=True, help_text='<span class="btn-layout-image-points-wrapper">Click <a id="btn-layout-image-points" href="#">HERE</a> for Points visual editor.</span>', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Interactive Maps',
            },
        ),
        migrations.CreateModel(
            name='InteractiveMapsLayoutPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=255)),
                ('left', models.FloatField(default=0, verbose_name='Left, %')),
                ('top', models.FloatField(default=0, verbose_name='Top, %')),
                ('visible', models.BooleanField(blank=True, default=1)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='interactivemaps.interactivemaps')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
