# Generated by Django 3.2.11 on 2022-06-09 13:20

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('interactivemaps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactivemapslayoutpoints',
            name='body',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Text'),
        ),
    ]
