# Generated by Django 3.2.11 on 2022-06-09 11:42

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='WtInstagramToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='You will be able to select this Token for the Social Media Page Items', max_length=255)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Instagram Token',
            },
        ),
        migrations.CreateModel(
            name='SocialContentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_datetime', models.DateTimeField(blank=True, null=True)),
                ('feed_user', models.CharField(blank=True, max_length=255, null=True)),
                ('feed_text', models.TextField(blank=True, null=True)),
                ('feed_status', models.CharField(blank=True, max_length=40, null=True)),
                ('feed_thumbnail', models.TextField(blank=True, null=True)),
                ('feed_dsc', models.CharField(blank=True, max_length=255, null=True)),
                ('feed_id', models.CharField(blank=True, max_length=255, null=True)),
                ('feed_link', models.TextField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=255, null=True)),
                ('invalid', models.BooleanField(default=True)),
                ('feed_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_content_items', to='wtinstagramtokens.wtinstagramtoken')),
            ],
        ),
    ]
