# Generated by Django 3.2.11 on 2022-06-12 07:17

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InteractiveGoogleMaps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Interactive Google Maps',
            },
        ),
        migrations.CreateModel(
            name='InteractiveGoogleMapPlaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=20)),
                ('places', wagtail.fields.StreamField([('places', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(icon='title', label='Title')), ('latitude', wagtail.blocks.CharBlock()), ('longitude', wagtail.blocks.CharBlock()), ('address', wagtail.blocks.TextBlock(required=False)), ('url', wagtail.blocks.URLBlock(required=False))], icon='pilcrow', label='Places'))])),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_groups', to='interactivegooglemaps.interactivegooglemaps')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
