# Generated by Django 3.2.11 on 2022-06-12 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactivegooglemaps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interactivegooglemaps',
            options={'verbose_name': 'Neighborhood Maps'},
        ),
    ]
