# Generated by Django 3.2.11 on 2022-06-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactivegooglemaps', '0002_alter_interactivegooglemaps_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactivegooglemaps',
            name='latitude',
            field=models.CharField(default='', max_length=255, verbose_name='Main Location latitude'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interactivegooglemaps',
            name='longitude',
            field=models.CharField(default='', max_length=255, verbose_name='Main Location longitude'),
            preserve_default=False,
        ),
    ]
