# Generated by Django 3.2.11 on 2022-06-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='towerbedroomtypes',
            name='sort_order',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
