# Generated by Django 3.2.11 on 2022-06-13 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('towers', '0002_towerbedroomtypes_sort_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='towerbedroomtypes',
            options={'ordering': ('sort_order',)},
        ),
    ]
