# Generated by Django 3.2.11 on 2022-06-13 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wtpages', '0015_alter_standardpage_stream_field'),
        ('towers', '0003_alter_towerbedroomtypes_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TowersIndexPage',
            fields=[
                ('wtbasepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wtpages.wtbasepage')),
            ],
            options={
                'verbose_name': 'Towers Index Page',
            },
            bases=('wtpages.wtbasepage',),
        ),
        migrations.CreateModel(
            name='TowerPage',
            fields=[
                ('standardpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wtpages.standardpage')),
                ('tower_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='towers.tower', verbose_name='Tower Type')),
            ],
            options={
                'verbose_name': 'Towers Index Page',
            },
            bases=('wtpages.standardpage',),
        ),
    ]
