# Generated by Django 3.2.11 on 2022-06-13 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wtpages', '0015_alter_standardpage_stream_field'),
        ('towers', '0004_towerpage_towersindexpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TowerInternalPage',
            fields=[
                ('standardpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wtpages.standardpage')),
            ],
            options={
                'verbose_name': 'Towers Internal Page',
            },
            bases=('wtpages.standardpage',),
        ),
    ]
