# Generated by Django 3.2.11 on 2022-06-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towers', '0030_auto_20220616_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='towerbedroomtypes',
            name='title_zh_hans',
            field=models.TextField(default='', verbose_name='Simplified Chinese Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='towerbedroomtypes',
            name='title_zh_hant',
            field=models.TextField(default='', verbose_name='Traditional Chinese Title'),
            preserve_default=False,
        ),
    ]
