# Generated by Django 3.2.11 on 2022-06-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towers', '0031_auto_20220616_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='towerview',
            name='title_zh_hans',
            field=models.TextField(default='', verbose_name='Simplified Chinese Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='towerview',
            name='title_zh_hant',
            field=models.TextField(default='', verbose_name='Traditional Chinese Title'),
            preserve_default=False,
        ),
    ]
