# Generated by Django 3.2.11 on 2022-06-17 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('towers', '0032_auto_20220617_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='towerview',
            name='title_zh_hans',
        ),
        migrations.RemoveField(
            model_name='towerview',
            name='title_zh_hant',
        ),
    ]
