# Generated by Django 3.2.11 on 2022-06-20 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('towers', '0033_auto_20220617_0305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='towerpage',
            options={'verbose_name': 'Tower Page'},
        ),
    ]
