# Generated by Django 3.2.11 on 2023-04-07 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towers', '0043_alter_sharedpageblocks_stream_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='towerbedroomtypes',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
