# Generated by Django 3.2.11 on 2023-04-07 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('towers', '0044_towerbedroomtypes_visible'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='towerbedroomtypes',
            options={'ordering': ('sort_order',), 'verbose_name': 'Tower Bedroom Type', 'verbose_name_plural': 'Tower Bedroom Types'},
        ),
    ]
