# Generated by Django 3.2.11 on 2023-05-01 16:21

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('towers', '0045_alter_towerbedroomtypes_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='towerplan',
            name='floorplates_images',
            field=wagtail.fields.StreamField([('images', wagtail.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock))], blank=True, null=True),
        ),
    ]
