# Generated by Django 3.2.11 on 2023-05-01 16:23

from django.db import migrations
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('towers', '0046_towerplan_floorplates_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='towerplan',
            name='floorplates_images',
            field=wagtail.fields.StreamField([('image', wagtail.images.blocks.ImageChooserBlock(label='Image'))], blank=True, null=True),
        ),
    ]
