# Generated by Django 3.2.11 on 2023-05-07 17:43

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('towers', '0047_alter_towerplan_floorplates_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='TowerPlanFloorPlateImageRendition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_hash', models.CharField(max_length=40)),
                ('tower_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='towers.towerplan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TowerPlanFloorPlateImageRenditionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('image', models.ImageField(upload_to='floorplates')),
                ('rendition', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='towers.towerplanfloorplateimagerendition')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
