# Generated by Django 3.2.11 on 2023-05-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towers', '0048_towerplanfloorplateimagerendition_towerplanfloorplateimagerenditionimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='towerplanfloorplateimagerenditionimage',
            name='image',
            field=models.ImageField(upload_to='images/floorplates'),
        ),
    ]
