# Generated by Django 3.2.11 on 2023-05-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towers', '0049_alter_towerplanfloorplateimagerenditionimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='towerplanfloorplateimagerenditionimage',
            name='image',
            field=models.ImageField(upload_to='floorplates'),
        ),
    ]
