# Generated by Django 3.2.11 on 2023-05-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towers', '0050_alter_towerplanfloorplateimagerenditionimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='towerplan',
            name='floorplates_images',
        ),
        migrations.AlterField(
            model_name='towerplanfloorplateimagerenditionimage',
            name='image',
            field=models.ImageField(upload_to='images/floorplates'),
        ),
    ]
