# Generated by Django 3.2.11 on 2023-07-12 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towers', '0051_auto_20230507_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='towerplan',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
