# Generated by Django 3.2.11 on 2023-10-18 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towers', '0055_alter_sharedpageblocks_stream_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='TowerPenthouseTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('title_zh_hans', models.TextField(verbose_name='Simplified Chinese Title')),
                ('title_zh_hant', models.TextField(verbose_name='Traditional Chinese Title')),
                ('sort_order', models.IntegerField(db_index=True, default=0)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tower Penthouse Type',
                'verbose_name_plural': 'Tower Penthouse Types',
                'ordering': ('sort_order',),
            },
        ),
    ]
