# Generated by Django 3.2.11 on 2023-10-18 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('towers', '0056_towerpenthousetypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='towerplan',
            name='penthouse_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='towers.towerpenthousetypes', verbose_name='For Penthouses Stream Field Block'),
        ),
    ]
