# Generated by Django 3.2.11 on 2023-10-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towers', '0058_auto_20231018_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='towerplan',
            name='total_sqft',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
