# Generated by Django 3.2.11 on 2023-11-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towers', '0059_towerplan_total_sqft'),
    ]

    operations = [
        migrations.AddField(
            model_name='towerview',
            name='penthouse_view',
            field=models.BooleanField(default=False, help_text='For View Widget, when Penthouses Only selected'),
        ),
    ]
