# Generated by Django 3.2.11 on 2022-06-09 11:42

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.blocks
import wagtail.fields
import wagtail.documents.blocks
import wtpages.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('wagtailimages', '0023_add_choose_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoBoxItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', wagtail.fields.RichTextField(blank=True, verbose_name='Text')),
                ('mode', models.CharField(choices=[('default', 'Text and Image'), ('image', 'Image Only'), ('text', 'Text Only')], default='default', max_length=20)),
                ('links_stream_field', wagtail.fields.StreamField([('internal_page_link', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(icon='title', label='Title')), ('link_type', wagtail.blocks.ChoiceBlock(choices=[('link', 'Link'), ('button', 'Button')], label='Link Type')), ('new_window', wagtail.blocks.BooleanBlock(label='Open link in new window', required=False)), ('link', wagtail.blocks.PageChooserBlock(label='Internal Page link', required=True))], icon='title', label='Internal Page Link')), ('external_page_link', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(icon='title', label='Title')), ('link_type', wagtail.blocks.ChoiceBlock(choices=[('link', 'Link'), ('button', 'Button')], label='Link Type')), ('new_window', wagtail.blocks.BooleanBlock(label='Open link in new window', required=False)), ('link', wagtail.blocks.URLBlock(label='External link', required=True))], icon='title', label='External Page Link')), ('phone_link', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(icon='title', label='Title')), ('link_type', wagtail.blocks.ChoiceBlock(choices=[('link', 'Link'), ('button', 'Button')], label='Link Type')), ('new_window', wagtail.blocks.BooleanBlock(label='Open link in new window', required=False)), ('link', wagtail.blocks.CharBlock(label='Phone Link', required=True))], icon='title', label='Phone Link')), ('email_link', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(icon='title', label='Title')), ('link_type', wagtail.blocks.ChoiceBlock(choices=[('link', 'Link'), ('button', 'Button')], label='Link Type')), ('new_window', wagtail.blocks.BooleanBlock(label='Open link in new window', required=False)), ('link', wagtail.blocks.EmailBlock(label='Email Link', required=True))], icon='title', label='Email Link')), ('form_link', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(icon='title', label='Title')), ('link_type', wagtail.blocks.ChoiceBlock(choices=[('link', 'Link'), ('button', 'Button')], label='Link Type')), ('new_window', wagtail.blocks.BooleanBlock(label='Open link in new window', required=False)), ('link', wtpages.blocks.FormChoserBlock(label='Pop Up Form link', required=True))], icon='title', label='Popup Form')), ('doc_link', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(icon='title', label='Title')), ('link_type', wagtail.blocks.ChoiceBlock(choices=[('link', 'Link'), ('button', 'Button')], label='Link Type')), ('new_window', wagtail.blocks.BooleanBlock(label='Open link in new window', required=False)), ('link', wagtail.documents.blocks.DocumentChooserBlock(label='Document', required=True))], icon='title', label='Document Link'))], blank=True, null=True)),
                ('show_logo', models.BooleanField(default=True)),
                ('visible', models.BooleanField(default=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PromoBoxItemPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('promo', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='wtpromobox.promoboxitem')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
