# Generated by Django 3.2.11 on 2024-01-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtpromobox', '0006_alter_promoboxitem_links_stream_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoboxitem',
            name='smaller_popup',
            field=models.BooleanField(default=False),
        ),
    ]
