# Generated by Django 3.2.11 on 2024-01-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtpromobox', '0007_promoboxitem_smaller_popup'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoboxitem',
            name='show_in_navigation',
            field=models.BooleanField(default=False),
        ),
    ]
