# Generated by Django 3.2.11 on 2024-01-26 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wtpromobox', '0008_promoboxitem_show_in_navigation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promoboxitem',
            name='show_in_navigation',
        ),
    ]
