# Generated by Django 3.2.11 on 2022-06-09 11:42

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormLinkPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Form Popup Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='FormPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('to_address', models.CharField(blank=True, help_text='Optional - form submissions will be emailed to these addresses. Separate multiple addresses by comma.', max_length=255, verbose_name='to address')),
                ('from_address', models.CharField(blank=True, max_length=255, verbose_name='from address')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='subject')),
            ],
            options={
                'verbose_name': 'Form',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='WtForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', wagtail.fields.RichTextField(blank=True)),
                ('thank_you_text', wagtail.fields.RichTextField(blank=True)),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('to_address', models.CharField(blank=True, help_text='Optional - form submissions will be emailed to these addresses. Separate multiple addresses by comma.', max_length=255, verbose_name='to address')),
                ('from_address', models.CharField(blank=True, max_length=255, verbose_name='from address')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='subject')),
                ('call_js_on_success', models.TextField(blank=True, null=True)),
                ('enable_recaptcha', models.BooleanField(default=False, verbose_name='Enable reCAPTCHA')),
                ('post_to_salesforce', models.BooleanField(default=False)),
                ('salesforce_url', models.URLField(blank=True, null=True)),
                ('post_to_revinate', models.BooleanField(default=False)),
                ('revinate_url', models.URLField(blank=True, null=True)),
                ('submit_button_title', models.CharField(blank=True, max_length=255, null=True)),
                ('captcha_sitekey', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Form',
            },
        ),
        migrations.CreateModel(
            name='WtFormField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.TextField(help_text='The label of the form field', verbose_name='label')),
                ('show_label', models.BooleanField(default=True)),
                ('field_type', models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('radio', 'Radio buttons'), ('date', 'Date'), ('time', 'Time'), ('datetime', 'Date/time'), ('captcha', 'Captcha'), ('file', 'File'), ('fieldsgroup', 'Fields Group'), ('stateselect', 'US State Select'), ('countryselect', 'Country Select'), ('dropdown2', 'Drop down (two drop downs)')], max_length=16, verbose_name='field type')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('choices', models.TextField(blank=True, help_text='New line separated list of choices. Only applicable in checkboxes, radio and dropdown.', verbose_name='choices')),
                ('choices2', models.TextField(blank=True, help_text='New line separated list of choices. Only applicable in Drop Down (two drop downs).', verbose_name='choices 2')),
                ('revinate_value_based_names', models.TextField(blank=True, help_text='New line separated list of choices. Only applicable in checkboxes, radio and dropdown.')),
                ('default_value', models.CharField(blank=True, help_text='Default value. New line separated values supported for checkboxes.', max_length=255, verbose_name='default value')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='help text')),
                ('add_css_class', models.CharField(blank=True, max_length=255, null=True, verbose_name='Add CSS class')),
                ('placeholder', models.CharField(blank=True, max_length=255, null=True, verbose_name='Placeholder')),
                ('salesforce_field', models.CharField(blank=True, max_length=255, null=True)),
                ('salesforce_field_type', models.CharField(choices=[('regular', 'Regular'), ('array', 'Array')], default='regular', max_length=20)),
                ('revinate_field', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WtFormHiddenField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WtFormRevinateTokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WtFormSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_data', models.TextField()),
                ('submit_time', models.DateTimeField(auto_now_add=True, verbose_name='submit time')),
            ],
            options={
                'verbose_name': 'Wt Form submission',
            },
        ),
        migrations.CreateModel(
            name='WtFormThankYouPages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('field_name', models.CharField(max_length=255)),
                ('field_value', models.CharField(max_length=255)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='thank_you_pages', to='wtforms.wtform')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
