# Generated by Django 3.2.11 on 2022-06-09 11:42

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wtpages', '0001_initial'),
        ('wtforms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wtformthankyoupages',
            name='thank_you_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wtpages.standardpage', verbose_name='Thank You Page'),
        ),
        migrations.AddField(
            model_name='wtformsubmission',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wtforms.wtform'),
        ),
        migrations.AddField(
            model_name='wtformrevinatetokens',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='revinate_tokens', to='wtforms.wtform'),
        ),
        migrations.AddField(
            model_name='wtformhiddenfield',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_fields', to='wtforms.wtform'),
        ),
        migrations.AddField(
            model_name='wtformfield',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='wtforms.wtform'),
        ),
        migrations.AddField(
            model_name='wtform',
            name='default_thank_you_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wtpages.standardpage', verbose_name='Default Thank You Page'),
        ),
        migrations.AddField(
            model_name='wtform',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wtpages.csstheme', verbose_name='Theme'),
        ),
        migrations.AddField(
            model_name='formlinkpage',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wtforms.wtform'),
        ),
    ]
