# Generated by Django 3.2.11 on 2022-06-14 07:24

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wtforms', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WtFormConditionalRotationFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('condition_field_name', models.CharField(max_length=255)),
                ('condition_field_value', models.CharField(max_length=255)),
                ('rotation_id', models.IntegerField()),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WtFormLassoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('lasso_id', models.IntegerField(db_index=True)),
                ('field_type', models.CharField(choices=[('checkbox', 'checkbox'), ('text', 'text'), ('single_select', 'single_select'), ('multi_select', 'multi_select'), ('date', 'date')], default='checkbox', max_length=20)),
            ],
            options={
                'verbose_name': 'Form Lasso Question',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='WtFormLassoListItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=255)),
                ('lasso_id', models.IntegerField(db_index=True)),
                ('list', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='wtforms.wtformlassolist')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='wtform',
            name='post_to_revinate',
        ),
        migrations.RemoveField(
            model_name='wtform',
            name='post_to_salesforce',
        ),
        migrations.RemoveField(
            model_name='wtform',
            name='revinate_url',
        ),
        migrations.RemoveField(
            model_name='wtform',
            name='salesforce_url',
        ),
        migrations.RemoveField(
            model_name='wtformfield',
            name='choices2',
        ),
        migrations.RemoveField(
            model_name='wtformfield',
            name='revinate_field',
        ),
        migrations.RemoveField(
            model_name='wtformfield',
            name='revinate_value_based_names',
        ),
        migrations.RemoveField(
            model_name='wtformfield',
            name='salesforce_field',
        ),
        migrations.RemoveField(
            model_name='wtformfield',
            name='salesforce_field_type',
        ),
        migrations.AddField(
            model_name='wtform',
            name='lasso_api_key',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='wtform',
            name='lasso_api_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wtform',
            name='lasso_client_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wtform',
            name='lasso_domain_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wtform',
            name='lasso_follow_up_process_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wtform',
            name='lasso_project_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wtform',
            name='lasso_secondary_source_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wtform',
            name='lasso_source_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wtform',
            name='lasso_uid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wtform',
            name='post_to_lasso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wtformfield',
            name='lasso_field_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wtformfield',
            name='related_input_class',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Related Input Name'),
        ),
        migrations.AlterField(
            model_name='wtformfield',
            name='field_type',
            field=models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('radio', 'Radio buttons'), ('date', 'Date'), ('time', 'Time'), ('datetime', 'Date/time'), ('captcha', 'Captcha'), ('file', 'File'), ('fieldsgroup', 'Fields Group'), ('sectiontitleh2', 'Section Title H2'), ('sectiontitleh3', 'Section Title H3')], max_length=16, verbose_name='field type'),
        ),
        migrations.AlterField(
            model_name='wtformfield',
            name='help_text',
            field=models.TextField(blank=True, verbose_name='help text'),
        ),
        migrations.DeleteModel(
            name='WtFormRevinateTokens',
        ),
        migrations.AddField(
            model_name='wtformconditionalrotationfields',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditional_rotation_fields', to='wtforms.wtform'),
        ),
        migrations.AddField(
            model_name='wtformfield',
            name='lasso_question_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wtforms.wtformlassolist', verbose_name='Lasso Question'),
        ),
    ]
