# Generated by Django 3.2.11 on 2022-06-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtforms', '0003_auto_20220614_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='wtformlassolistitems',
            name='title_sc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Simplified Chinese'),
        ),
        migrations.AddField(
            model_name='wtformlassolistitems',
            name='title_tc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Traditional Chinese'),
        ),
    ]
