# Generated by Django 3.2.11 on 2022-06-20 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wtforms', '0004_auto_20220620_0251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wtformlassolistitems',
            name='title_sc',
        ),
        migrations.RemoveField(
            model_name='wtformlassolistitems',
            name='title_tc',
        ),
    ]
