# Generated by Django 5.2.15 on 2026-06-29 08:58

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtforms', '0006_alter_formpage_from_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wtform',
            name='form_body',
            field=wagtail.fields.StreamField([('singleline', 9), ('multiline', 9), ('email', 9), ('number', 9), ('url', 9), ('date', 9), ('time', 9), ('datetime', 9), ('checkbox', 9), ('dropdown', 12), ('radio', 12), ('checkboxes', 12), ('file', 9), ('captcha', 9), ('fieldsgroup', 9), ('sectiontitleh2', 9), ('sectiontitleh3', 9)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {'label': 'Label'}), 1: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'label': 'Show label', 'required': False}), 2: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'label': 'Required', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Default value', 'required': False}), 4: ('wagtail.blocks.TextBlock', (), {'label': 'Help text', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Add CSS class', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Placeholder', 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'label': 'Related Input Name', 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Lasso Field Name', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('label', 0), ('show_label', 1), ('required', 2), ('default_value', 3), ('help_text', 4), ('add_css_class', 5), ('placeholder', 6), ('related_input_class', 7), ('lasso_field_name', 8)]], {}), 10: ('wagtail.blocks.TextBlock', (), {'help_text': 'New line separated list of choices.', 'label': 'Choices', 'required': False}), 11: ('wagtail.snippets.blocks.SnippetChooserBlock', ('wtforms.WtFormLassoList',), {'label': 'Lasso Question List', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('label', 0), ('show_label', 1), ('required', 2), ('default_value', 3), ('help_text', 4), ('add_css_class', 5), ('placeholder', 6), ('related_input_class', 7), ('lasso_field_name', 8), ('choices', 10), ('lasso_question_list', 11)]], {})}, verbose_name='Form fields (StreamField)'),
        ),
        migrations.AddField(
            model_name='wtform',
            name='use_streamfield',
            field=models.BooleanField(default=False, verbose_name='Use StreamField for form fields'),
        ),
    ]
