# Generated by Django 5.2.15 on 2026-06-29 08:58

import uuid
from unidecode import unidecode
from django.utils.text import slugify
from django.db import migrations


def migrate_form_fields_to_streamfield(apps, schema_editor):
    WtForm = apps.get_model("wtforms", "WtForm")
    WtFormField = apps.get_model("wtforms", "WtFormField")

    for form in WtForm.objects.prefetch_related("form_fields").all():
        fields = form.form_fields.order_by("sort_order")
        if not fields.exists():
            continue

        stream_data = []
        for field in fields:
            clean_name = "%s-%s" % (slugify(str(unidecode(field.label))), field.pk)

            value = {
                "_legacy_clean_name": clean_name,
                "label": field.label,
                "show_label": field.show_label,
                "required": field.required,
                "default_value": field.default_value or "",
                "help_text": field.help_text or "",
                "add_css_class": field.add_css_class or "",
                "placeholder": field.placeholder or "",
                "related_input_class": field.related_input_class or "",
                "lasso_field_name": field.lasso_field_name or "",
            }

            # Choices for dropdown/radio/checkboxes
            if field.field_type in ("dropdown", "radio", "checkboxes"):
                value["choices"] = field.choices or ""
                if field.lasso_question_list_id:
                    value["lasso_question_list"] = field.lasso_question_list_id

            stream_data.append({
                "type": field.field_type,
                "value": value,
                "id": uuid.uuid4().hex,
            })

        form.form_body = stream_data
        form.use_streamfield = True
        form.save(update_fields=["form_body", "use_streamfield"])


def reverse_migrate(apps, schema_editor):
    WtForm = apps.get_model("wtforms", "WtForm")
    WtForm.objects.filter(use_streamfield=True).update(
        form_body="[]",
        use_streamfield=False,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("wtforms", "0007_add_streamfield_form_body"),
    ]

    operations = [
        migrations.RunPython(
            migrate_form_fields_to_streamfield,
            reverse_migrate,
        ),
    ]
