# Generated by Django 3.2.11 on 2022-06-09 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WtFavicon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('faviconImage', models.ImageField(upload_to='favicon')),
                ('isFavicon', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Favicon',
                'verbose_name_plural': 'Favicons',
            },
        ),
        migrations.CreateModel(
            name='WtFaviconImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('rel', models.CharField(max_length=250, null=True)),
                ('faviconImage', models.ImageField(upload_to='favicon')),
                ('faviconFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wtfavicon.wtfavicon')),
            ],
        ),
    ]
