# Generated by Django 3.2.11 on 2022-06-09 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='WtSitemap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('generic', 'Use Generic Sitemap'), ('custom', 'Use Uploaded Sitemap')], default='generic', max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to='sitemaps', verbose_name='Sitemap file')),
                ('robots', models.TextField(blank=True, default='User-agent: *\nDisallow: /admin/', help_text='User-agent: *\nDisallow: /admin/', verbose_name='robots.txt')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Sitemap',
            },
        ),
    ]
