# Generated by Django 3.2.11 on 2022-06-09 11:42

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.blocks
import wagtail.fields
import wagtail.documents.blocks
import wtpages.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wtpages', '0001_initial'),
        ('wthomepage', '0001_initial'),
        ('wagtailimages', '0023_add_choose_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageRootPage',
            fields=[
                ('standardpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wtpages.standardpage')),
                ('footer_legal', wagtail.fields.RichTextField(blank=True, null=True)),
                ('page_404_text', wagtail.fields.RichTextField(blank=True, verbose_name='Page Not Found Text')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('footer_links', wagtail.fields.StreamField([('internal_page_link', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(icon='title', label='Title')), ('link_type', wagtail.blocks.ChoiceBlock(choices=[('link', 'Link'), ('button', 'Button')], label='Link Type')), ('new_window', wagtail.blocks.BooleanBlock(label='Open link in new window', required=False)), ('link', wagtail.blocks.PageChooserBlock(label='Internal Page link', required=True))], icon='title', label='Internal Page Link')), ('external_page_link', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(icon='title', label='Title')), ('link_type', wagtail.blocks.ChoiceBlock(choices=[('link', 'Link'), ('button', 'Button')], label='Link Type')), ('new_window', wagtail.blocks.BooleanBlock(label='Open link in new window', required=False)), ('link', wagtail.blocks.URLBlock(label='External link', required=True))], icon='title', label='External Page Link')), ('phone_link', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(icon='title', label='Title')), ('link_type', wagtail.blocks.ChoiceBlock(choices=[('link', 'Link'), ('button', 'Button')], label='Link Type')), ('new_window', wagtail.blocks.BooleanBlock(label='Open link in new window', required=False)), ('link', wagtail.blocks.CharBlock(label='Phone Link', required=True))], icon='title', label='Phone Link')), ('email_link', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(icon='title', label='Title')), ('link_type', wagtail.blocks.ChoiceBlock(choices=[('link', 'Link'), ('button', 'Button')], label='Link Type')), ('new_window', wagtail.blocks.BooleanBlock(label='Open link in new window', required=False)), ('link', wagtail.blocks.EmailBlock(label='Email Link', required=True))], icon='title', label='Email Link')), ('form_link', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(icon='title', label='Title')), ('link_type', wagtail.blocks.ChoiceBlock(choices=[('link', 'Link'), ('button', 'Button')], label='Link Type')), ('new_window', wagtail.blocks.BooleanBlock(label='Open link in new window', required=False)), ('link', wtpages.blocks.FormChoserBlock(label='Pop Up Form link', required=True))], icon='title', label='Popup Form')), ('doc_link', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(icon='title', label='Title')), ('link_type', wagtail.blocks.ChoiceBlock(choices=[('link', 'Link'), ('button', 'Button')], label='Link Type')), ('new_window', wagtail.blocks.BooleanBlock(label='Open link in new window', required=False)), ('link', wagtail.documents.blocks.DocumentChooserBlock(label='Document', required=True))], icon='title', label='Document Link'))], blank=True, null=True)),
                ('contact_page_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wtpages.standardpage')),
                ('page_404_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Home Page',
            },
            bases=('wtpages.standardpage',),
        ),
        migrations.CreateModel(
            name='LanguageRootPageFooterSocialLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=255)),
                ('language_code', models.CharField(choices=[('en', 'English'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese')], default='en-us', max_length=10)),
                ('fontawesome_icon', models.CharField(blank=True, help_text='Set any icon listed there https://fontawesome.com/v4.7.0/icons/', max_length=50, null=True)),
                ('link', models.URLField()),
                ('new_window', models.BooleanField(default=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_social_links', to='wthomepage.languagerootpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
