# Generated by Django 3.2.11 on 2022-06-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wthomepage', '0002_languagerootpage_languagerootpagefootersociallinks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='languagerootpage',
            options={'verbose_name': 'Language Root Page'},
        ),
        migrations.AddField(
            model_name='languagerootpage',
            name='language_code',
            field=models.CharField(choices=[('en', 'English'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese')], default='en-us', max_length=20),
        ),
    ]
