# Generated by Django 3.2.11 on 2022-06-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wthomepage', '0003_auto_20220609_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagerootpage',
            name='contact_page_title',
            field=models.CharField(default='Register', max_length=255, verbose_name='Register Link Title'),
        ),
    ]
