# Generated by Django 3.2.11 on 2022-06-14 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wthomepage', '0004_languagerootpage_contact_page_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='languagerootpage',
            name='contact_page_title',
        ),
        migrations.RemoveField(
            model_name='languagerootpagefootersociallinks',
            name='language_code',
        ),
    ]
