# Generated by Django 3.2.11 on 2022-06-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wthomepage', '0005_auto_20220614_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagerootpage',
            name='language_code',
            field=models.CharField(choices=[('en-us', 'English'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese')], default='en-us', max_length=20),
        ),
    ]
