# Generated by Django 3.2.11 on 2022-06-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wthomepage', '0006_alter_languagerootpage_language_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagerootpage',
            name='language_code',
            field=models.CharField(choices=[('en-us', 'English'), ('zh-hant', 'Traditional Chinese'), ('zh-hans', 'Simplified Chinese')], default='en-us', max_length=20),
        ),
    ]
