# Generated by Django 3.2.11 on 2022-06-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wthomepage', '0007_alter_languagerootpage_language_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagerootpage',
            name='page_404_title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
