# Generated by Django 3.2.11 on 2022-07-21 04:59

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.documents.blocks
import wtpages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wthomepage', '0008_languagerootpage_page_404_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagerootpage',
            name='footer_links',
            field=wagtail.fields.StreamField([('internal_page_link', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(icon='title', label='Title')), ('link_type', wagtail.blocks.ChoiceBlock(choices=[('link', 'Link'), ('button', 'Button'), ('reverse', 'Inverted Button')], label='Link Type')), ('new_window', wagtail.blocks.BooleanBlock(label='Open link in new window', required=False)), ('link', wagtail.blocks.PageChooserBlock(label='Internal Page link', required=True))], icon='title', label='Internal Page Link')), ('external_page_link', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(icon='title', label='Title')), ('link_type', wagtail.blocks.ChoiceBlock(choices=[('link', 'Link'), ('button', 'Button'), ('reverse', 'Inverted Button')], label='Link Type')), ('new_window', wagtail.blocks.BooleanBlock(label='Open link in new window', required=False)), ('link', wagtail.blocks.URLBlock(label='External link', required=True))], icon='title', label='External Page Link')), ('phone_link', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(icon='title', label='Title')), ('link_type', wagtail.blocks.ChoiceBlock(choices=[('link', 'Link'), ('button', 'Button'), ('reverse', 'Inverted Button')], label='Link Type')), ('new_window', wagtail.blocks.BooleanBlock(label='Open link in new window', required=False)), ('link', wagtail.blocks.CharBlock(label='Phone Link', required=True))], icon='title', label='Phone Link')), ('email_link', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(icon='title', label='Title')), ('link_type', wagtail.blocks.ChoiceBlock(choices=[('link', 'Link'), ('button', 'Button'), ('reverse', 'Inverted Button')], label='Link Type')), ('new_window', wagtail.blocks.BooleanBlock(label='Open link in new window', required=False)), ('link', wagtail.blocks.EmailBlock(label='Email Link', required=True))], icon='title', label='Email Link')), ('form_link', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(icon='title', label='Title')), ('link_type', wagtail.blocks.ChoiceBlock(choices=[('link', 'Link'), ('button', 'Button'), ('reverse', 'Inverted Button')], label='Link Type')), ('new_window', wagtail.blocks.BooleanBlock(label='Open link in new window', required=False)), ('link', wtpages.blocks.FormChoserBlock(label='Pop Up Form link', required=True))], icon='title', label='Popup Form')), ('doc_link', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(icon='title', label='Title')), ('link_type', wagtail.blocks.ChoiceBlock(choices=[('link', 'Link'), ('button', 'Button'), ('reverse', 'Inverted Button')], label='Link Type')), ('new_window', wagtail.blocks.BooleanBlock(label='Open link in new window', required=False)), ('link', wagtail.documents.blocks.DocumentChooserBlock(label='Document', required=True))], icon='title', label='Document Link'))], blank=True, null=True),
        ),
    ]
