# Generated by Django 3.2.11 on 2024-01-10 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wtpages', '0061_auto_20231122_0043'),
        ('wthomepage', '0013_alter_languagerootpage_footer_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagerootpage',
            name='penthouse_collections_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wtpages.standardpage'),
        ),
    ]
