# Generated by Django 3.2.11 on 2024-01-26 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wtpromobox', '0009_remove_promoboxitem_show_in_navigation'),
        ('wthomepage', '0014_languagerootpage_penthouse_collections_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagerootpage',
            name='promo_box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wtpromobox.promoboxitem'),
        ),
    ]
